include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_print: warning

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    sort_constructors_first: true
